[package]
name = "rust_tokenizer"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_tokenizer"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19", features = ["extension-module"] }